[project]
version = "0.1.0"
name = "net"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[dependencies]
string = "1"
err = "1"
byteorder = "1"
io = "1"
pool = "1"

[variants]
default = []
